[EMMUII-113] add admin role and access validation
FrontSpot-Community/code-verify pull request #50
Opened 2018-06-07 20:37 UTC by VladCherniavsky

2018-07-14 14:35 UTC, SergeyKovalchuk requested changes

2018-07-14 14:35 UTC, SergeyKovalchuk commented on app/middlewares/checkAccess.js
> +
remove, please, excessive line space

2018-07-14 14:35 UTC, SergeyKovalchuk commented on app/middlewares/checkAuthentication.js
> +      return next(createError(unauthorized.message, unauthorized.statusCode));
You are trying to incapsulate the same error as in a global catch statement. It would be great to do it once or use another global error

2018-07-18 21:24 UTC, VladCherniavsky commented on app/middlewares/checkAccess.js
> +
@SergeyKovalchuk Thanks for your attention ,fixed.

2018-07-18 21:24 UTC, VladCherniavsky commented on app/middlewares/checkAuthentication.js
> +      return next(createError(unauthorized.message, unauthorized.statusCode));
Fixed

2018-07-19 11:32 UTC, SergeyKovalchuk submitted a review, later dismissed

2018-07-20 10:41 UTC, merged