Feature/EPMUII-123
FrontSpot-Community/code-verify pull request #52
Opened 2018-07-13 15:11 UTC by Dmitry-White

2018-07-14 14:22 UTC, SergeyKovalchuk requested changes
Please fix this right after merge of https://github.com/FrontSpot-Community/code-verify/pull/53

2018-07-14 14:22 UTC, SergeyKovalchuk commented on app/libs/commonCrudOperations.js
> +    const select = findBy
The same as for https://github.com/FrontSpot-Community/code-verify/pull/53

2018-07-15 13:23 UTC, VladCherniavsky commented on app/routers/tournament.router.js
> +router.post('/tournament/:id', remove);
Please use `delete` instead of `post`

2018-07-17 10:55 UTC, SergeyKovalchuk commented
Too many commits let's squash

2018-07-17 20:31 UTC, egor-miasnikov commented
Also could you please use rebase against merge?

2018-07-23 14:39 UTC, merged